-- 'users' table

CREATE TABLE users (
    is_active BOOLEAN, 
    created TIMESTAMP(6),
    last_login TIMESTAMP(6)
    modified TIMESTAMP(6)
    id UUID NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULl,
    token VARCHAR(255),
    primary key (id)
)

-- 'phones' table

CREATE TABLE phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID,
    citycode VARCHAR(255) NOT NULL, 
    countrycode VARCHAR(255) NOT NULL,
    number VARCHAR(255) NOT NULL, 
    primary key (id)
)

-- foreign key relationship
ALTER TABLE phones
    ADD CONSTRAINT FKmg6d77tgqfen7n1g763nvsqe3
    FOREIGN KEY (user_id) REFERENCES users;